name: rabbitmq-test-tool
contact: nicolas.bock@canonical.com
issues: https://github.com/nicolasbock/rabbitmq-test-tool/issues
source-code: https://github.com/nicolasbock/rabbitmq-test-tool.git
summary: RabbitMQ-Test-Tool
description: |
  A simple test script to test a RabbitMQ cluster.
icon: rabbit.png
base: core18
confinement: strict
adopt-info: rabbitmq-test-tool
license: BSD-3-Clause
grade: stable

apps:
  rabbitmq-test-tool:
    command: bin/rabbitmq-test-tool
    plugs:
      - network-bind
      - docker

parts:
  rabbitmq-test-tool:
    plugin: python
    source: .
    build-packages:
      - git
    requirements:
      - requirements.txt
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(bin/get_version.py)"
